name: otaqu
description: Created by Dani Rycki Dinata
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  dartz: ^0.10.1
  bottom_navy_bar: ^6.0.0
  animations: ^2.0.3

  # Common packages
  nb_utils: ^6.0.0
  google_fonts: ^5.1.0
  lottie: ^2.4.0

  # State Management Technique
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # Singleton instance
  get_it: ^7.2.0

  # Network Stuff
  dio: ^5.3.2
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  json_serializable: ^6.5.4
  jwt_decoder: ^2.0.1

  # Persistance Data
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/icons/
